version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        volumes:
            - .:/app
            - '/app/node_modules'

    mysql:
        image: mysql:8.0
        environment:
            - MYSQL_DATABASE=test_db
            - MYSQL_USER=test_user
            - MYSQL_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=root